__luaver_install_lua: indicate error by exit code

diff --git a/luaver b/luaver
--- a/luaver
+++ b/luaver
@@ -215,6 +215,11 @@ __luaver_uninstall()
 }
 
 # Returns the platform
+# Synopsis:
+#     __luaver_get_platform
+# Exit status:
+#     0   if platform was successfully determined
+#     1   if platform could not be determined
 __luaver_get_platform()
 {
     case $(uname -s 2>/dev/null) in
@@ -225,7 +230,7 @@ __luaver_get_platform()
         CYGWIN* | MINGW* | MSYS* ) echo "mingw" ;;
         AIX )                      echo "aix" ;;
         SunOS )                    echo "solaris" ;;
-        * )                        echo "unknown"
+        * )                        return 1
     esac
 }
 
@@ -333,43 +338,45 @@ __luaver_usage()
     __luaver_print_formatted "   luaver uninstall 5.3.0                   # Uninstalls lua version 5.3.0"
 }
 
+# Synopsis:
+#     __luaver_install_lua version [baseurl] [archive_path]
+# Exit status:
+#     0   if successfully installed
+#     1   if any error is occurred
 __luaver_install_lua()
 {
-    local version=$1
-    local lua_dir_name="lua-${version}"
-    local archive_name="${lua_dir_name}.tar.gz"
-    local url="http://www.lua.org/ftp/${archive_name}"
+    set -- "${1:?}" "${2-http://www.lua.org/ftp}" "${__luaver_SRC_DIR}/lua-${1}.tar.gz"
 
-    __luaver_print "Installing ${lua_dir_name}"
-
-    __luaver_exec_command cd "${__luaver_SRC_DIR}"
-
-    __luaver_download "${url}" &&
-    __luaver_unpack "${archive_name}" "${lua_dir_name}"
+    __luaver_print "Installing lua-${1}"
 
     __luaver_print "Detecting platform"
-    platform=$(__luaver_get_platform)
-    if [ "${platform}" = "unknown" ]
+    if __luaver_get_platform >/dev/null 2>&1
     then
-        __luaver_print "Unable to detect platform. Using default 'posix'"
-        platform=posix
+        __luaver_print "Platform detected: $(__luaver_get_platform)"
     else
-        __luaver_print "Platform detected: ${platform}"
+        __luaver_print "Unable to detect platform. Using default 'posix'"
     fi
 
-    __luaver_exec_command cd "${lua_dir_name}"
+    __luaver_download "${2}/lua-${1}.tar.gz" "${3}" &&
+    __luaver_unpack "${3}" "lua-${1}" "${3%/*}" &&
+    if (
+        __luaver_print "Compiling lua-${1}"
+        'cd' "${3%/*}/lua-${1}" &&
+        'make' "$(__luaver_get_platform || echo "posix")" install INSTALL_TOP="${__luaver_LUA_DIR}/${1}"
+    )
+    then
+        __luaver_print "lua-${1} successfully installed. Do you want to switch to this version? [Y/n]: "
+        read -r choice
+        case $choice in
+            [yY][eE][sS] | [yY] )
+                __luaver_use_lua "${1}"
+                ;;
+        esac
 
-    __luaver_print "Compiling ${lua_dir_name}"
-
-    __luaver_exec_command make "${platform}" install INSTALL_TOP="${__luaver_LUA_DIR}/${version}"
-
-    __luaver_print "${lua_dir_name} successfully installed. Do you want to switch to this version? [Y/n]: "
-    read -r choice
-    case $choice in
-        [yY][eE][sS] | [yY] )
-            __luaver_use_lua "${version}"
-            ;;
-    esac
+        return 0
+    else
+        return 1
+    fi
 }
 
 __luaver_use_lua()
